### ISSUE TITLE
cannot compile FADT tables

### ISSUE THREAD

**Issue by tycho** [acpica/acpica#385] opened 2018-05-14 10:14 UTC
I can't compile FACP.dsl (a decompiled FADT table from my BIOS) with iasl, and the message is extraordinarily unhelpful:

```
$ iasl FACP.dsl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180105
Copyright (c) 2000 - 2018 Intel Corporation

Error    6126 -  Could not compile input file

Table Input:   FACP.dsl - 164 lines, 9229 bytes, 136 fields

Compilation complete. 1 Errors, 0 Warnings, 0 Remarks
```

I used GDB to figure out where it was breaking, and I ended up doing the following patch to make it work. The output looks fine, but I'm not sure why the change is necessary to begin with.
```diff
diff --git a/source/compiler/dtcompile.c b/source/compiler/dtcompile.c
index a850993..52f4302 100644
--- a/source/compiler/dtcompile.c
+++ b/source/compiler/dtcompile.c
@@ -479,7 +479,7 @@ DtCompileDataTable (
         /* Complex table, has a handler */
 
         Status = TableData->CmTableHandler ((void **) FieldList);
-        if (ACPI_FAILURE (Status))
+        if (ACPI_FAILURE (Status) && Status != AE_END_OF_TABLE)
         {
             return (Status);
         }
```

**Comment by tycho** [comment] 2018-05-16 02:35
I've attached two tables (FADT and TPM2) from the same system that are exhibiting this problem and are fixed by the patch I used above.

[FACP.zip](https://github.com/acpica/acpica/files/2007329/FACP.zip)
[TPM2.zip](https://github.com/acpica/acpica/files/2007330/TPM2.zip)

**Comment by acpibob** [comment] 2018-05-16 19:49
Both of these tables have problems, and won’t even disassemble properly:

// ACPI Warning: FADT revision 5 does not match length: found F4 expected 10C

TPM2:

/**** ACPI table terminates in the middle of a data structure! (dump table) */

**Comment by tycho** [comment] 2018-05-16 19:53
Weird. They disassemble locally?

**Comment by tycho** [comment] 2018-05-16 19:56
Oh. They disassemble (create an output file) but have that same message.
Ugly.

**Comment by acpibob** [comment] 2018-05-16 21:02
Can you send the original binaries? We can take a look.

I admit that the data table compiler is rather weak on error handling/messages. It is on our list of TBD improvements.
Bob

**Comment by tycho** [comment] 2018-05-16 22:10
The original ACPI table binaries? What I attached were ripped straight from
/sys/firmware/acpi/tables...

**Comment by acpibob** [comment] 2018-05-17 14:30
The ones you sent are the .DSL files, which are the disassembled tables, not the original binary tables. The binary tables should have a file extension something like .DAT or .BIN

I’m not sure how to obtain the binary tables on Linux, but you should at least be able to get the acpidump for the tables, which would be a help.

**Comment by acpibob** [comment] 2018-05-17 15:27
Some further information:


1)      FADT: Set the version number of the FADT to 2. The problem is that it is set to version 5, which has more required fields than are present in the original table. This then compiles.

[008h 0008   1]                     Revision : 02


2)      TPM2: The “Start Method” in the table is 2, but the TPM2 spec doesn’t seem to define the structure of any “Start Method” value other than 11. So, that is the only value that is supported in iASL. We may be misunderstanding this, so we are looking at it again.

[030h 0048   4]                 Start Method : 02 [ACPI Start Method]


In any case, the DataTableCompiler portion of iASL needs improvement in the error reporting area, and is on our list of things to do.

**Comment by tycho** [comment] 2018-05-17 15:35
Sorry, I don't know how I managed to zip the wrong files. Totally intended to send the original bins.

[tables.zip](https://github.com/acpica/acpica/files/2013837/tables.zip)

**Comment by SchmErik** [comment] 2018-10-19 18:55
TPM2 is an incorrect data table. Here's a little snippet from the TCG ACPI specification https://trustedcomputinggroup.org/wp-content/uploads/TCG_ACPIGeneralSpecification_v1.20_r8.pdf page 16/23:
```
If the Start Method value is 2, then this field is at least four bytes in size and the first four bytes must be all zero.
```
Your ACPI dump has only 3 bytes past the Start Method value and that's why we have the error. I know that the error messages aren't the most helpful but it attempted to tell you in the disassembly: 
```

[024h 0036   2]               Platform Class : 0000
[026h 0038   2]                     Reserved : 0000
[028h 0040   8]              Control Address : 00000000AFFFF000
[030h 0048   4]                 Start Method : 02 [ACPI Start Method]

/**** ACPI table terminates in the middle of a data structure! (dump table) */

Raw Table Data: Length 52 (0x34)
```

**Comment by SchmErik** [comment] 2018-10-19 20:14
Actually, your TPM2 table is revision 3. The spec I referenced is revision 4. Another user had this problem. Let's track the TPM2 issue at issue #404

**Comment by SchmErik** [comment] 2018-10-23 21:17
I found the issue with your FADT. FADT is a static table and it has a fixed length. Your FACP is missing these fields at the very end (note these values may not be accurate for your stystem... but you could try it and see what happens):
```
[0F4h 0244  12]       Sleep Control Register : [Generic Address Structure]
[0F4h 0244   1]                     Space ID : 00 [SystemMemory]
[0F5h 0245   1]                    Bit Width : 00
[0F6h 0246   1]                   Bit Offset : 00
[0F7h 0247   1]         Encoded Access Width : 00 [Undefined/Legacy]
[0F8h 0248   8]                      Address : 0000000000000000

[100h 0256  12]        Sleep Status Register : [Generic Address Structure]
[100h 0256   1]                     Space ID : 00 [SystemMemory]
[101h 0257   1]                    Bit Width : 00
[102h 0258   1]                   Bit Offset : 00
[103h 0259   1]         Encoded Access Width : 00 [Undefined/Legacy]
[104h 0260   8]                      Address : 0000000000000000
```
We understand that the error messages are aren't very helpful. We're working on addressing this issue by replacing the front-end of the current data table compiler with a flex/bison implementation. I'll close this for now since this is an actual error in your FACP. I am still working on finding the TPM2 rev 3 definition but let's talk about that in #404 .

**Closed by SchmErik** 2018-10-23 21:17 UTC
