### ISSUE TITLE
 Setting Semaphore to NULL Warnings on Haiku

### ISSUE THREAD

**Issue by tqh** [acpica/acpica#162] opened 2016-08-07 11:02 UTC
On Haiku `ACPI_SEMAPHORE` is `sem_id` (32 bit int).
Setting them to `NULL` causes
  `warning: assignment makes integer from pointer without a cast`

Is there any simple way to fix it worth the small benefit of building on Haiku without warnings?
Casting `NULL` to `ACPI_SEMAPHORE` creates a warning for losing precision (64 to 32 bit).

Log:

```
.../acpica/components/utilities/utdelete.c: In function 'AcpiUtDeleteInternalObj':
.../acpica/components/utilities/utdelete.c:260:41: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
             AcpiGbl_GlobalLockSemaphore = NULL;
                                         ^
.../acpica/components/utilities/utdelete.c:279:35: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
         Object->Event.OsSemaphore = NULL;
                                   ^
.../acpica/components/utilities/utinit.c: In function 'AcpiUtInitGlobals':
.../acpica/components/utilities/utinit.c:283:41: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     AcpiGbl_GlobalLockSemaphore         = NULL;
```

**Comment by acpibob** [comment] 2016-08-26 16:04
I suppose that a special, configurable NULL could be created just for the semaphores. Call it:

ACPI_SEMAPHORE_NULL

default would be:
#define ACPI_SEMAPHORE_NULL    NULL
Haiku case would be:
#define ACPI_SEMAPHORE_NULL    0

Would this work for you?

**Comment by tqh** [comment] 2017-02-27 20:02
Sorry for the slow response. Yes that would work best. We'd use -1 for the Haiku define though.
I did try to make a pointer to the id, but the code became overly complex.

**Comment by acpibob** [comment] 2017-03-23 19:40
Does a similar issue happen with mutex objects?

**Comment by acpibob** [comment] 2017-03-23 19:49
also, spinlocks?

**Comment by tqh** [comment] 2017-03-23 19:52
No, they are all fine.
Our only changes to build with warnings as errors enabled are these:
https://github.com/haiku/haiku/commit/d78cf60aca28fe2a239388d6b32589011c11fe21

**Comment by acpibob** [comment] 2017-12-06 16:29
Sounds like the issue is resolved, closing

**Closed by acpibob** 2017-12-06 16:29 UTC
