### ISSUE TITLE
iASL -dl option returns more comments than normal

### ISSUE THREAD

**Issue by mirh** [acpica/acpica#243] opened 2017-03-26 16:17 UTC
DSDT is the [usual one](https://github.com/acpica/acpica/issues/173#issuecomment-245526031). 
Look for example where EECD method is defined. 

`-dl` correctly (?) comments \/* \_SB_.PCI0.SBRG.EC0_.P6CH *\/, while output without this switch lacks it.

**Comment by acpibob** [comment] 2017-03-27 19:18
The comment itself is correct:
- find p6ch
         \_SB.PCI0.SBRG.EC0.P6CH RegionField  006D6E48 01 Rgn [EC6C] Off 000 Len 08 Acc 01

Not sure why the ASL disassembly (-dl) would have different comments than ASL+ (default) disassembly.
This seems to a very old issue, however, perhaps going back as far as the creation of ASL+ support.

At least as far back as version 20141107

**Comment by acpibob** [comment] 2017-03-27 19:29
Here is the actual issue:

Legacy (ASL) disassembly:
Store (Arg0, P6CH) /* \_SB_.PCI0.SBRG.EC0_.P6CH */

ASL+ disassembly:
P6CH = Arg0

**Comment by mirh** [comment] 2018-02-11 17:56
Still a thing in 20180209.

**Comment by mirh** [comment] 2018-02-13 00:35
I'm saying that with *-dl* I'm getting (rightly?): `Store (Arg0, P6CH) /* \_SB_.PCI0.SBRG.EC0_.P6CH */`
With just *-d* the line is only: `P6CH = Arg0`

**Comment by SchmErik** [comment] 2018-02-13 17:55
Yes you are correct. When you use -dl, we get
`Store (Arg0, P6CH) /* \_SB_.PCI0.SBRG.EC0_.P6CH */`
with just -d, we get 
`P6CH = Arg0`

If we try this with a named object rather than Arg0, we get this with -dl
`Store (ABCD, P6CH) /* \_SB_.PCI0.SBRG.EC0_.P6CH */`
and with -d, we get this:
`P6CH = ABCD /* \ABCD */`

What's happening with -d is that the comment is printed for the source object rather than the target. This is the opposite for -dl. For -dl, the comment is printed for the target object.

**Comment by mirh** [comment] 2018-02-13 18:17
Mhh.. Indeed I just noticed the different behavior of e.g. LocalX, compared to ArgX. 

So.. Is this like intended behavior then?

**Comment by SchmErik** [comment] 2018-02-13 18:48
We could try to be more clear and put both named objects in the comment

**Comment by SchmErik** [comment] 2018-10-18 17:31
For now, we will say that this is the intended behavior. Closing

**Closed by SchmErik** 2018-10-18 17:31 UTC
