### ISSUE TITLE
iasl -d failed to decompile PMEM ssdt

### ISSUE THREAD

**Issue by limulidae** [acpica/acpica#583] opened 2020-04-07 01:06 UTC
`
Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200326
Copyright (c) 2000 - 2020 Intel Corporation

File appears to be binary: found 12550 non-ASCII characters, disassembling
Binary file appears to be a valid ACPI table, disassembling
Input file ssdt6.dat, Length 0x7954 (31060) bytes
ACPI: SSDT 0x0000000000000000 007954 (v02 HPE    HPE PMEM 00000002 HPE  00020000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)
Firmware Error (ACPI): Failure creating named object [\_SB.NVDR._DSM.STAT], AE_ALREADY_EXISTS (20200326/dsfield-347)

NULL byte list in buffer
NULL byte list in buffer
Parsing completed

Found 1 external control methods, reparsing with new information
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed

[ssdt6.dat.txt](https://github.com/acpica/acpica/files/4441489/ssdt6.dat.txt)

`

**Comment by SchmErik** [comment] 2020-04-07 17:37
This looks like an incorrect encoding of the buffer SSRB buffer and we cannot disassemble this SSDT

**Comment by SchmErik** [comment] 2020-04-10 16:48
There's another reporter that reported the same thing. I'm working on this issue now...

**Comment by SchmErik** [comment] 2020-04-10 21:20
fix available here: https://github.com/acpica/acpica/pull/590

**Comment by limulidae** [comment] 2020-04-12 02:00
When can we get a new release with this fix?

**Comment by SchmErik** [comment] 2020-04-13 17:23
we do a release roughly once per month so I would expect this pull request to be released at toward the end of this month. @acpibob do you have any dates in mind?

**Comment by santino-wang** [comment] 2020-04-16 06:54
Thanks fo the quick fix!

Is this bug caused by our asl programming practice so it lead to iasl compatible issue?

**Comment by SchmErik** [comment] 2020-04-16 17:36
It's a little complicated but basically yes. HPE's compiler generated AML that the disassembler is not used to seeing. The disassembler is not used to seeing this kind of code because it is disallowed by our iASL compiler because its a little more conservative. This does not cause an error in the AML interpreter because the disassembler and interpreter evaluates the AML in a different way

**Comment by SchmErik** [comment] 2020-06-03 16:58
Closing as this has been fixed in acpica version 20200430

**Closed by SchmErik** 2020-06-03 16:58 UTC
