### ISSUE TITLE
Endless file generation when dumping special tables like RSDP, DSDT, etc.

### ISSUE THREAD

**Issue by smwikipedia** [acpica/acpica#285] opened 2017-06-28 15:02 UTC
[Symptom]:
I ported acpidump to UEFI Shell environment. When dumping special tables like RSDP, RSDT, XSDT, DSDT, FACS, acpidump.efi will generate too many files until it reaches AP_MAX_ACPI_FILES = 256.

This issue doesn't happen with normal tables like BERT, HEST. And doens't happen when dump table by index.

[Root cause]: 
These special tables are all singleton. But there's no necessary detection when dump them with instance number > 1.

**Comment by acpibob** [comment] 2017-06-28 15:25
It does sound like a problem, but why are you using instance > 1?

**Comment by smwikipedia** [comment] 2017-06-28 15:42
I am not using instance > 1. I just use the following command line:
acpidump.efi -b -n DSDT
And it will generate many dsdt.dat files. All identical.

The reason is, when use -n to dump a table by name, it will treat every talbe as potentially having multiple instances. It loops through 0 to AP_MAX_ACPI_FILES to call the AcpiOsGetTableByName(). For normal tables, there's a detection logic for excessive instnace number. For special tables like DSDT, there's not, so redundent files are generated.

**Comment by acpibob** [comment] 2017-06-28 15:49
Here's what I see on win:

c:\temp>acpidump -b -n DSDT

 Directory of c:\temp

06/28/2017  08:44 AM    <DIR>          .
06/28/2017  08:44 AM    <DIR>          ..
06/28/2017  08:44 AM           126,458 dsdt.dat
06/28/2017  08:42 AM           734,476 dump.txt

I'll take a look at the code, but I'm not seeing any bad behavior. What version of acpidump are you using? here's the current version:

c:\temp>acpidump -v

Intel ACPI Component Architecture
ACPI Binary Table Dump Utility version 20170531
Copyright (c) 2000 - 2017 Intel Corporation

**Comment by smwikipedia** [comment] 2017-06-28 15:50
Yes, on windows it's fine. The issue is with efi porting. The issue file is "\source\os_specific\efi\osefitbl.c". Function OslGetTable().

**Comment by acpibob** [comment] 2017-06-28 15:53
Lv can have a look at this.

**Comment by acpibob** [comment] 2017-06-28 15:54
Probably best if you open a bugzilla on this at

https://bugs.acpica.org

And point out that the problem is against the EFI version.
Thanks.

**Comment by smwikipedia** [comment] 2017-06-28 15:57
I will contact him tomorrow.

**Comment by zetalog** [comment] 2017-06-29 00:36
DSDT could have 2 instances, one for 32-bit OS, the other for 64-bit OS. That's why we allow to dump DSDT with instances.

**Comment by acpibob** [comment] 2017-06-29 01:48
How many files are generated? 
It sounds like 256?

**Comment by zetalog** [comment] 2017-06-30 00:50
Filed a bug and posted a fix here:

https://bugs.acpica.org/show_bug.cgi?id=1407

**Comment by zetalog** [comment] 2017-06-30 00:58
> How many files are generated? It sounds like 256?
Yes, EFI support contains a very old bug.

Originally acpidump is developed to support 2 instances of DSDT/FACS but it's not tested and broken. On Linux we changed to support only 1 instance of DSDT/FACS when a bug was reported. But EFI support is not fixed.

Actually we should support 2 instances, as FACS/XFACS do contain different content. I tried to improve both Linux and EFI support.

**Comment by smwikipedia** [comment] 2017-07-05 22:56
yes, from the logic, maximum 256 files can be generated.




发自网易邮箱大师
On 06/30/2017 08:58, zetalog wrote:

How many files are generated? It sounds like 256?
Yes, EFI support contains a very old bug.

Originally acpidump is developed to support 2 instances of DSDT/FACS but it's not tested and broken. On Linux we changed to support only 1 instance of DSDT/FACS when a bug was reported. But EFI support is not fixed.

Actually we should support 2 instances, as FACS/XFACS do contain different content. I tried to improve both Linux and EFI support.

**Comment by acpibob** [comment] 2017-09-08 16:27
Can we close this?

**Comment by acpibob** [comment] 2017-12-01 20:38
Closing.

**Closed by acpibob** 2017-12-01 20:38 UTC
