### ISSUE TITLE
When iasl reads DOS format files on Unix (e.g., in EDK2), it can't handle continuations

### ISSUE THREAD

**Issue by ahs3** [acpica/acpica#423] opened 2018-10-25 02:57 UTC
For example, you can create a template IORT table on Linux with:

    $ iasl -T IORT

Then, convert it to DOS format:

    $ unix2dos iort.asl

When you try to recompile it, you get:

    Intel ACPI Component Architecture
    ASL+ Optimizing Compiler/Disassembler version 20181003
    Copyright (c) 2000 - 2018 Intel Corporation
    
    iort.asl     55: [0084]                            Padding :  \
    Error    6300 -      Invalid element in buffer initializer list ^  (\)
    
    Table Input:   iort.asl - 179 lines, 8287 bytes, 146 fields

If you remove the '\', this compiles fine.  Or, if the file is in Unix format, it compiles without changing anything.

This has apparently been true for several releases but is definitely in the current code.

**Comment by SchmErik** [comment] 2018-10-25 18:05
> For example, you can create a template IORT table on Linux with:
> 
> ```
> $ iasl -T IORT
> ```
> 
> Then, convert it to DOS format:
> 
> ```
> $ unix2dos iort.asl
> ```
> 
> When you try to recompile it, you get:
> 
> ```
> Intel ACPI Component Architecture
> ASL+ Optimizing Compiler/Disassembler version 20181003
> Copyright (c) 2000 - 2018 Intel Corporation
> 
> iort.asl     55: [0084]                            Padding :  \
> Error    6300 -      Invalid element in buffer initializer list ^  (\)
> 
> Table Input:   iort.asl - 179 lines, 8287 bytes, 146 fields
> ```
> 
> If you remove the '', this compiles fine. Or, if the file is in Unix format, it compiles without changing anything.

Hi Al!

I'll assume you meant '\\'. I'm taking a look at this right now
> 
> This has apparently been true for several releases but is definitely in the current code.

**Comment by SchmErik** [comment] 2018-10-25 19:08
#425 should solve the problem. It seems to work for me but go ahead and give it a try

**Comment by SchmErik** [comment] 2018-10-25 19:16
@acpibob could you do "iasl -T iort" and "iasl iort.asl"? I want to make sure that is an error on windows as well..

**Comment by acpibob** [comment] 2018-10-25 19:53
Works fine on Windows

c:\0acpi-tables\IORT\>iasl -T iort
Created ACPI table template for [IORT], written to "iort.asl"

c:\0acpi-tables\IORT\>iasl iort.asl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20181003
Copyright (c) 2000 - 2018 Intel Corporation

Table Input:   iort.asl - 179 lines, 8286 bytes, 146 fields
Binary Output: iort.aml - 524 bytes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks

**Comment by ahs3** [comment] 2018-10-26 15:10
> > iort.asl     55: [0084]                            Padding :  \
> > Error    6300 -      Invalid element in buffer initializer list ^  (\)
> > 
> > Table Input:   iort.asl - 179 lines, 8287 bytes, 146 fields
> > ```
> > If you remove the '', this compiles fine. Or, if the file is in Unix format, it compiles without changing anything.
> 
> Hi Al!

Hey, Erik!

> I'll assume you meant '\'. I'm taking a look at this right now

Thanks!  Y'all have to more OS environments than I do, otherwise I would have tried to patch this myself.

> > This has apparently been true for several releases but is definitely in the current code.

Yeah, I tried the last three (maybe four) and found the same issue.

**Comment by acpibob** [comment] 2018-10-26 17:10
We attempt to open the input ASL file in Text Mode, which should automatically convert DOS CR/LF line endings to Unix LF endings.

Upon closer examination, we don’t understand what the problem is.

BTW, we have executed your example below, and this works fine on Cygwin, but does not work on Fedora.

Do you have any ideas about this?

Thanks,
Bob/Eric

**Comment by SchmErik** [comment] 2018-10-29 16:17
@ahs3  I've updated #425 with a better solution

**Comment by SchmErik** [comment] 2018-10-30 17:50
this fix will be in the next release

**Comment by SchmErik** [comment] 2018-10-30 17:51
Closing. It works on my side. Feel free to reopen if you see any issues with it.

**Closed by SchmErik** 2018-10-30 17:51 UTC

**Comment by ahs3** [comment] 2018-12-20 00:03
> Closing. The fix is working on my side. Feel free to reopen if you see any issues with it.

Thanks, Erik.  That does the trick -- sorry for the delay in responding.
